### ISSUE TITLE
Create JUnit Tests for BGP-LS Messages, objects and TLVs

### ISSUE THREAD

**Issue by oscargdd** [telefonicaid/netphony-network-protocols#4]

**Comment by oscargdd** [comment]
Added tests for BGP-LS MP Reach Attributes with Node NLRI. Pending tests with Link NLRI

**Comment by lixisha** [comment]
Hello, i'm very interested in netphony-network-protocols library. 
I have tried some example about creating  BGP-LS packet, 
but when i use the Wireshark to capture the packet, 
I found a 'Continuation' field which is 29 bytes. I wonder about what it is
Could you explain it for me ? Thank you very much!

**Comment by oscargdd** [comment]
Hi! Can you send the sample code and the pcap trace, so I can take a look at that field?

**Comment by lixisha** [comment]
Thank you for your response!



Please check the attachment about pcap trace.
I used netty library 3.9

Thank you very much!


Regards,

Li, Xisha
Supervised by professor Jin Seek Choi.
MIR Lab. Department of Computer Science and Engineering
Hanyang University
Seoul, KOREA 133-791
+82-010-8285-8911
[wiresharkAndCode.zip](https://github.com/telefonicaid/netphony-network-protocols/files/816648/wiresharkAndCode.zip)

**Comment by oscargdd** [comment]
I have opened the pcap trace in wireshark and it looks good. Here is the screenshot:
![wireshark_update_dissection](https://cloud.githubusercontent.com/assets/3374866/23550622/4deea122-0012-11e7-84a6-9c8c8a27590a.png)
hot.

**Comment by oscargdd** [comment]
I saw it... it appeard before the UPDATE message.. Let me check... first time to see it ,  
![continuation](https://cloud.githubusercontent.com/assets/3374866/23550746/e10f7a6c-0012-11e7-8fea-a0f420dc3351.png)

**Comment by lixisha** [comment]
It seems like that the BGP-LS format is correct.Maybe there is something wrong with the wireshark dissector?ps: I have used netty (version 3.10.5.final) with ObjectEncoder/ObjectDecoder to test the library.Regards,Li, XishaSupervised by professor Jin Seek Choi.MIR Lab. Department of Computer Science and EngineeringHanyang UniversitySeoul, KOREA 133-791+82-010-8285-8911
------ Original Message ------
Date: Friday, Mar 3, 2017 09:11:50 PM

**Comment by oscargdd** [comment]
The problem I see in you traces is that, in every packet sent, before the BGP-LS packet there are a set of bytes sent, always the same. You need to check what are you sending in your java code. Once you have enconded the message, you have the bytes to be sent. Check the number of bytes (or even print them) and compare against what you are capturing in wireshark. Maybe there is something in your code sending some bytes before every packet...
